name: webdev_proxy
version: 0.1.7
private: true
homepage: https://github.com/Workiva/webdev_proxy

description: >
  A simple HTTP proxy for webdev's serve command. Supports apps that use HTML5
  routing by rewriting 404s to the root index.

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  args: '>=1.5.1 <3.0.0'
  http: ^0.13.0
  http_multi_server: ^2.1.0
  io: '>=0.3.3 <2.0.0'
  logging: '>=0.11.3+2 <2.0.0'
  meta: ">=1.1.7 <1.7.0" # pin to avoid issue in 1.7.0
  pedantic: ^1.7.0
  pub_semver: '>=1.4.2 <3.0.0'
  shelf: ^1.0.0
  shelf_proxy: ^1.0.0
  stack_trace: ^1.9.3

dev_dependencies:
  # These two build deps are required by webdev.
  build_runner: '>=1.5.1 <3.0.0'
  build_web_compilers: '>=2.12.0 <3.0.0'

  shelf_static: ^0.2.8
  sse: ^4.0.0
  test: ^1.6.3
  webdriver: ^3.0.0

executables:
  webdev_proxy:
