name: webdev_proxy
version: 0.1.8
private: true
homepage: https://github.com/Workiva/webdev_proxy

description: >
  A simple HTTP proxy for webdev's serve command. Supports apps that use HTML5
  routing by rewriting 404s to the root index.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  glob: ^2.0.1
  http: ^0.13.3
  http_multi_server: ^3.2.1
  io: ^1.0.3
  logging: ^1.1.0
  meta: ^1.8.0
  lints: ^2.0.1
  pub_semver: ^2.1.2
  shelf: ^1.2.0
  shelf_proxy: ^1.0.0
  stack_trace: ^1.10.0

dev_dependencies:
  # These two build deps are required by webdev.
  build_runner: ^2.1.2
  build_web_compilers: ^3.0.0

  shelf_static: ^1.1.0
  sse: ^4.1.0
  test: ^1.17.12
  webdriver: ^3.0.0

executables:
  webdev_proxy:
